/// ============================================================================
/// Exercise 04 - GitHub Features - BUGFIX CHALLENGE
/// ============================================================================
/// This file contains a measure with a REAL BUG that needs fixing!
/// 
/// Business requirement: Calculate revenue growth % compared to previous month
/// Problem: The measure will ERROR in certain scenarios
/// 
/// Your task:
/// 1. Find the bug
/// 2. Fix it
/// 3. Commit and create a PR with Copilot's help

table sales_sample

	/// % Revenue Growth Measure - This is one of Mari's measures.
	/// 
	/// This measure calculates the percentage change in revenue
	/// compared to the previous month.
	measure '% Revenue Growth' =
			VAR CurrentRevenue = [Total Revenue]
			VAR PreviousRevenue = 
			    CALCULATE(
			        [Total Revenue],
			        DATEADD(sales_sample[order_date], -1, MONTH)
			    )
			RETURN
			    DIVIDE(CurrentRevenue - PreviousRevenue, PreviousRevenue, 0)
		formatString: 0.0%
		displayFolder: KPIs
		lineageTag: 40000000-0000-0000-0000-000000000001
